### ISSUE TITLE
missing build file

### ISSUE THREAD

**Issue by gtonkinhill** [knightjimr/SeroCall#1]
Hi,

I'm trying to build a database but the file genomeOnly/T4J_genomeOnly_R1_001.fastq.gz doesn't appear to be available. Is there somewhere I could download it from?

Thanks

**Comment by knightjimr** [comment]
My apologies.  It looks like the server I'm using stopped allowing wildcards in the URL's, and there was another bug for the build script, but I have updated the URL and tested the script, and it should work for you now.  Let me know if it doesn't.

**Comment by gtonkinhill** [comment]
Thank you very much! It's working now.
